version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

  app:
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
    container_name: app
    environment:
      - DBURL=${DBURL}
    ports:
      - ${GOAPP_EXTERNAL_PORT}:80
    networks:
      - backend

  postgres:
    image: postgres:${DB_DOCKER_VERSION}
    container_name: postgres
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    ports:
      - ${DB_EXTERNAL_PORT}:${DBPORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
