version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

  app:
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
    container_name: app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      # External port : Internal port
      - ${PORT}:80
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=genesis
    ports:
      # External port : Internal port
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
