version: "3"

dotenv: [".env.development"]

vars:
  BINARY: genesis

tasks:
  genrsa:
    desc: Generate RSA keys for JWT auth
    cmds:
      - openssl genrsa -out app.rsa 1024
      - openssl rsa -in app.rsa -pubout > app.rsa.pub

  goose:
    desc: Run goose migrations (usage, task goose -- cmd=up|down|status|up-to|down-to version=123)
    vars:
      cmd: '{{.cmd | default "status"}}'
      version: '{{.version | default ""}}'
    cmds:
      - |
        if [ -n "{{.version}}" ]; then
          goose -dir migrations {{.DBENGINE}} "{{.DATABASE_URL}}" {{.cmd}} {{.version}}
        else
          goose -dir migrations {{.DBENGINE}} "{{.DATABASE_URL}}" {{.cmd}}
        fi

  test:
    desc: Execute tests
    cmds:
      - sqlc generate
      - go test ./...

  swagger:
    desc: Generate Swagger documentation
    cmds:
      - swag fmt -d rest/
      - swag init -g rest/router.go

  debug:
    desc: Build binary for debugging with IDE
    cmds:
      - sqlc generate
      - go build -gcflags "-N -l" -o {{.BINARY}} .

  build:
    desc: Build binary
    deps: [swagger]
    cmds:
      - sqlc generate
      - go build -o {{.BINARY}} cmd/main/*.go

  clean:
    desc: Remove the binary file generated
    cmds:
      - rm -f {{.BINARY}}
