// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int64
	Uuid      pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type InvoiceHeader struct {
	ID        int64
	Uuid      pgtype.UUID
	ClientID  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type InvoiceItem struct {
	ID              int64
	InvoiceHeaderID int32
	ProductID       int32
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Product struct {
	ID           int64
	Uuid         pgtype.UUID
	Name         string
	Observations pgtype.Text
	Price        int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type User struct {
	ID        int64
	Uuid      pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
