// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
	"time"

	"github.com/pborman/uuid"
)

type Customer struct {
	ID        int64
	Uuid      uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type InvoiceHeader struct {
	ID        int64
	Uuid      uuid.UUID
	ClientID  int64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type InvoiceItem struct {
	ID              int64
	InvoiceHeaderID int64
	ProductID       int64
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

type Product struct {
	ID           int64
	Uuid         uuid.UUID
	Name         string
	Observations string
	Price        int64
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type User struct {
	ID        int64
	Uuid      uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
