basePath: /v1/
definitions:
  http.respError:
    properties:
      error:
        type: string
    type: object
  http.respOkData:
    properties:
      data: {}
      ok:
        type: string
    type: object
  http.userProfileDTO:
    properties:
      email:
        example: johndoe@aol.com
        type: string
      firstName:
        example: John
        type: string
      id:
        example: 1
        type: integer
      lastName:
        example: Doe
        type: string
    type: object
  http.userSignUpForm:
    properties:
      email:
        example: johndoe@aol.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      password:
        example: 1234567b
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: adrianolmedo.ve@gmail.com
    name: Adrián Olmedo
    url: https://twitter.com/adrianolmedo
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Genesis REST API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register a user
      parameters:
      - description: application/json
        in: body
        name: userSignUpForm
        required: true
        schema:
          $ref: '#/definitions/http.userSignUpForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/http.respOkData'
            - properties:
                data:
                  $ref: '#/definitions/http.userProfileDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.respError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.respError'
      summary: SignUp User
swagger: "2.0"
